name: GitHub Actions Deploy
run-name: ${{ github.actor }} is deploying the application
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Nodejs
        run: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
      - name: Install Yarn
        run: corepack enable
      - name: Run yarn; install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
