name: GitHub Actions Deploy
run-name: ${{ github.actor }} is deploying the application
on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# only allow one of these jobs at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Nodejs
        run: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
      - name: Install Yarn
        run: corepack enable
      - name: Run yarn; install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build static files
        run: yarn build
      - run: ls -l dist
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v1
